name: Build TVLive123 Java32
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 第一步：安装JDK17，用来运行sdkmanager（下载Android SDK工具）
      - name: Setup JDK17 for sdkmanager
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Python 3.8
        id: python38
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Android SDK & NDK（此时JDK是17，可以正常运行sdkmanager）
        uses: android-actions/setup-android@v3

      # 下载SDK完成，切换JDK为11，用来编译TVLive123项目！
      - name: Switch to JDK11 for project build
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 替换国内Maven镜像，加速依赖下载
        run: |
          sed -i 's|https://repo.maven.apache.org/maven2|https://maven.aliyun.com/repository/public|g' build.gradle
          sed -i 's|https://plugins.gradle.org/m2|https://maven.aliyun.com/repository/gradle-plugin|g' build.gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Java32Release（armv7a minSdk4.4）
        run: |
          export PYTHON38_HOME=${{ steps.python38.path }}
          ./gradlew assembleJava32Release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TVLive123-Java32-APK
          path: output/apk/*.apk
